# Generated by Django 4.1.3 on 2022-12-05 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_title_topic_quiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='p_name',
            new_name='t_name',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='p_name',
            new_name='t_name',
        ),
    ]
