# Generated by Django 4.1.3 on 2022-12-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_p_name_question_t_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='t_name',
            field=models.CharField(max_length=60),
        ),
    ]
